### ISSUE TITLE
Moonscraper crashing on Launch

### ISSUE THREAD

**Issue by AlanDunaway** [FireFox2000000/Moonscraper-Chart-Editor#95] opened 2022-12-18 17:03 UTC
Hello.

I just downloaded Moonscraper and started it, as soon as it opens, an alert shows up and the app closes out of nowhere.
![image](https://user-images.githubusercontent.com/96152972/208310090-660ce2b7-7964-448d-bbbf-0dfffffa66ee.png)
Right after this alert, the app closes.
Tried both with and without administrator permissions.
It doesn't let me do anything, not even load an audio, this alert shows up as soon as the main window opens.

**Comment by FireFox2000000** [comment] 2023-01-14 11:16
Please provide the following information

1. The version number of Moonscraper this bug was found in (as found in the title of the window or in the "About" section).

2. The OS platform the application was running on (Windows/Linux)

3. Include any crash dumps or output_log.txt files if available. The output_log.txt can be located under AppData\LocalLow\FireFox Dev\Moonscraper Chart Editor after a Moonscraper session has successfully closed, or in the crash dump folder if the application crashed.
Note that Moonscraper v1.0 will not produce an output_log.txt.
Note that for versions below 1.3.1 the output_log can be found under the "Moonscraper Chart Editor_Data" folder.

**Comment by AlanDunaway** [comment] 2023-01-15 07:32
Okay, here's the info:
Moonscraper version is in the screenshot, 1.4.4.
[Moonscraper Log](https://drive.google.com/file/d/1P5MZg-wvb86dM78Vsi2kbMVUT25YIT-4/view?usp=share_link)(Google Drive link)
Windows 10 Professional 22H2(Compilation 19045.2486).
Hope this info helps.
Thank you.

**Comment by FireFox2000000** [comment] 2023-01-16 10:53
Was there a crash report generated under `C:/Users/user/AppData/Local/Temp/FireFox Dev/Moonscraper Chart Editor/Crashes`? If so could you provide that as well?

**Comment by AlanDunaway** [comment] 2023-01-16 11:20
Sorry, there is no folder named **Crashes** in there. There are only a few folders related to Moonscraper projects, but they are all empty.

**Comment by FireFox2000000** [comment] 2023-06-02 10:39
Please attempt to see if the issue is resolved in the newest test build v1.5.0.2- https://drive.google.com/file/d/1xxakW8rbiwAa1DoX-L-m0mjpBBntfn7C/view?usp=share_link

**Comment by AlanDunaway** [comment] 2023-06-02 17:02
1.5.0.2 works fine. Took a little while to show the track on first launch. Subsequent launches show the track quite instantly.

**Closed** 2023-06-02 17:08 UTC
Labels: bug
