### ISSUE TITLE
I tried booting it up for linux but this happened

### ISSUE THREAD

**Issue by Average-FNF-Fan** [FireFox2000000/Moonscraper-Chart-Editor#104] opened 2023-05-13 21:23 UTC
Here is a screenshot of what it says: 
![Screenshot from 2023-05-13 16-22-24](https://github.com/FireFox2000000/Moonscraper-Chart-Editor/assets/132780133/aa0b8f75-508a-4bf6-aa1c-b2eee502470d)

No matter what I do, i dont know how to fix it. i tried spamming yes and it just kept popping up, i tried resetting and everything i could think of.

**Comment by FireFox2000000** [comment] 2023-06-02 10:29
Duplicate of #62

**Closed by FireFox2000000** 2023-06-02 10:29 UTC
